
name: Add comment to new issue

on:
  issues:
    types: [opened, labeled]

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment for bug
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you. We will fix it.'
            })
      - name: Add comment for feature
        if: contains(github.event.issue.labels.*.name, 'feature')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you, we will consider to include this feature.'
            })
      - name: Add comment for discussion
        if: contains(github.event.issue.labels.*.name, 'discussion')
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for starting this discussion! We welcome community input.'
            })
